apiVersion: v1
kind: Service
metadata:
  name: quarkus-app-workshop
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: quarkus-app-workshop
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: quarkus-app-workshop
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: quarkus-app-workshop